# Generated by Django 2.1.1 on 2018-09-29 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_bank', models.CharField(max_length=200)),
                ('ifsc_code', models.CharField(max_length=20, null=True)),
                ('account_number', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_name', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('check', 'By Check'), ('cash', 'By Cash')], max_length=4)),
                ('transaction_date', models.DateField()),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dairy_Natural_Milk.Bank')),
            ],
        ),
    ]
